In [10]:
load("HH-of-T3.sage")

In [4]:
S = SL2Z.0
T = SL2Z.1

In [6]:
Monica_table([T^k for k in [0,1,2,3,4,12]],6)

  ()                ()      (1,2)      (1,2)(3,4)   (1,2)(3,4)(5,6)   (1,2,3)    (1,2,3)(4,5)   (1,2,3)(4,5,6)   (1,2,3,4)   (1,2,3,4)(5,6)   (1,2,3,4,5)   (1,2,3,4,5,6)
  [1 0]
[0 1]       ()      ()         ()           ()                ()         ()             ()               ()          ()               ()            ()
  [1 1]
[0 1]       ()      (2,)       (2,)         (2,)              (3,)       (6,)           (3,)             (4,)        (2, 4)           (5,)          (6,)
  [1 2]
[0 1]       (2,)    (2, 4)     (2, 4)       (4,)              (2, 6)     (2, 2, 12)     (6,)             (2, 8)      (4, 8)           (2, 10)       (12,)
  [1 3]
[0 1]       (3,)    (3, 6)     (3, 6)       (6,)              (3, 9)     (3, 3, 18)     (9,)             (3, 12)     (6, 12)          (3, 15)       (18,)
  [1 4]
[0 1]       (4,)    (4, 8)     (4, 8)       (8,)              (4, 12)    (4, 4, 24)     (12,)            (4, 16)     (8, 16)          (4, 20)       (24,)
  [ 1 12]
[ 0  1]   (12,)   (12, 24)   (12, 24)     (24,)             (12, 36)   (12, 12, 72)   (36,)            (12, 48)    (24, 48)         (12, 60)      (72,)

In [11]:
Monica_table([T^k for k in [0,1,2,3,4,12]],6,False)

  ()                ()                         (1,2)                  (1,2)(3,4)         (1,2)(3,4)(5,6)   (1,2,3)            (1,2,3)(4,5)   (1,2,3)(4,5,6)   (1,2,3,4)      (1,2,3,4)(5,6)   (1,2,3,4,5)   (1,2,3,4,5,6)
  [1 0]
[0 1]       ()                         ()                     ()                 ()                ()                 ()             ()               ()             ()               ()            ()
  [1 1]
[0 1]       ()                         (2,)                   (2, 2)             (2, 2, 2)         (3,)               (6,)           (3, 3)           (4,)           (2, 4)           (5,)          (6,)
  [1 2]
[0 1]       (2, 2, 2, 2, 2, 2)         (2, 2, 2, 2, 4)        (2, 2, 4, 4)       (4, 4, 4)         (2, 2, 2, 6)       (2, 2, 12)     (6, 6)           (2, 2, 8)      (4, 8)           (2, 10)       (12,)
  [1 3]
[0 1]       (3, 3, 3, 3, 3, 3)         (3, 3, 3, 3, 6)        (3, 3, 6, 6)       (6, 6, 6)         (3, 3, 3, 9)       (3, 3, 18)     (9, 9)           (3, 3, 12)     (6, 12)          (3, 15)       (18,)
  [1 4]
[0 1]       (4, 4, 4, 4, 4, 4)         (4, 4, 4, 4, 8)        (4, 4, 8, 8)       (8, 8, 8)         (4, 4, 4, 12)      (4, 4, 24)     (12, 12)         (4, 4, 16)     (8, 16)          (4, 20)       (24,)
  [ 1 12]
[ 0  1]   (12, 12, 12, 12, 12, 12)   (12, 12, 12, 12, 24)   (12, 12, 24, 24)   (24, 24, 24)      (12, 12, 12, 36)   (12, 12, 72)   (36, 36)         (12, 12, 48)   (24, 48)         (12, 60)      (72,)

Guess: When we don't take coinvariants, HH_0 is isomorphic to the product of \Z/\lambda_i where \lamba_i ranges over the parts of \lambda_i (this time counting multiples)